### ISSUE TITLE
Amfora v1.7.2

### ISSUE THREAD

**Issue by makew0rld** [jedahan/kiss-repo#2]
Amfora v1.7.2 has been released. Thanks!

**Comment by jedahan** [comment]
fixed in https://github.com/jedahan/kiss-repo/commit/ab7fd4f33278da0d25bbb61535699d49ab4d7d58 , thanks for the announcement

**Comment by makew0rld** [comment]
You're welcome. Feel free "Watch" the GitHub releases of Amfora to be notified of new versions.
